import type { NextPage } from 'next'
import React from "react";
import Head from 'next/head'

// const Title = dynamic(() => import('ui/Title'))
import Title from 'ui/Title'

const Login: NextPage = () => {
  // const { count, increment, decrement } = useStore()

  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Title text="Login" />
        {/* <Layout>
          <Counter count={count} onIncrement={increment} onDecrement={decrement} />
        </Layout> */}
      </main>
    </>
  )
}

Login.getInitialProps = async (ctx) => {
  return { ctx };
}

export default Login
