import type { NextPage } from 'next'
import React from 'react'
import Head from 'next/head'
import dynamic from 'next/dynamic'

// const Title = dynamic(() => import('ui/Title'))
import Title from 'ui/Title'

const Home: NextPage = ({ data }: any) => {

  // const { count, increment, decrement } = useStore()
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Title text="Home s" />
        {data && <h3><span style={{ fontWeight: 'bold' }}>Data from API:</span> {JSON.stringify(data)}</h3>}
        {/* <Layout>
          <Counter count={count} onIncrement={increment} onDecrement={decrement} />
        </Layout> */}
      </main>
    </>
  )
}

Home.getInitialProps = async (ctx) => {
  const res = await fetch('https://jsonplaceholder.typicode.com/todos/1');
  const data = await res.json();
  return { ctx, data };
}

export default Home