import type { NextPage } from 'next'
import dynamic from 'next/dynamic';
import Head from 'next/head'

// Federated imports
const useStore = (await import('../fed-store/uiStore')).default
const Layout = dynamic(() => import('../fed-components/uiLayout'))
const Header = dynamic(() => import('../fed-components/uiHeader'))
const Nav = dynamic(() => import('../fed-components/uiNav'))
const Title = dynamic(() => import('../fed-components/uiTitle'))
const Counter = dynamic(() => import('../fed-components/uiCounter'))

const Login: NextPage = () => {

  const { count, increment, decrement } = useStore()

  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <Layout>
          <Header>
            <Nav />
          </Header>
          <Title text="Login" />
          <Counter count={count} onIncrement={increment} onDecrement={decrement} />
        </Layout>
      </main>
    </>
  )
}

Login.getInitialProps = async (ctx) => {
  return { ctx };
}

export default Login
